### ISSUE TITLE
Path To Nauvis

### ISSUE THREAD

**Issue by Noble61x** [nicholasgower/planet-muluna#7]
I'm all for new planets/moons etc, but maybe dont make the moon a mandatory path to get to Nauvis. And for some reason the mod resets my Cargo Bay and Asteroi Collector research. And not sure if its the pathing with the mandatory Muluna before Nauvis but any space platform going to or from Nauvis just stops, wont go foward or baclwards.

**Comment by nicholasgower** [comment]
Since this planet, unlike other planet mods, goes before any of the core space-age planets, it is more difficult to add this mod to an existing save than other planet mods. This mod adds a stage of space platform building that goes between building a rocket silo and the rest of space age. During this stage, asteroid collectors are not available yet, so your first couple of ships must be supplied by constant shipments from below. For existing saves, I can write a migration that minimizes the impact of adding the mod to an existing save, but it will still break space science platforms, as the mod is intended to move space science to Muluna. I should make the nature of this mod clearer, that it works best when added to a save that has not left Nauvis yet.

I believe the problem you're experiencing is that you have added this mod to an existing save, and because you have not unlocked Muluna yet, The path between Nauvis and the rest of your planets is broken.

It looks like another issue(#8) makes it impossible to unlock Muluna at the moment. I'd recommend waiting for this mod to become more playable before adding it to an existing save.

**Comment by nicholasgower** [comment]
Can you send me the save you tried to install this mod on? I will need as many saves as possible to make sure my migration covers all bases.

**Comment by YPetremann** [comment]
I think the Noble61x's problem is that even after asteroid collectors are researched, it still needed to travel through muluna

The fact that muluna would not be a mandatory passage point would make it break less.

**Comment by nicholasgower** [comment]
The act of moving space connections outside of the Nauvis system from Nauvis to Muluna has been made into an optional setting disabled by default.
